import { motion } from "motion/react"
import { Link } from "react-router"
import { Sparkles, Download } from "lucide-react"
import { QuizBadge } from "@/app/components/shared/QuizBadge"
import { PillButton } from "@/app/components/shared/PillButton"
import { ColorSwatch } from "@/app/components/shared/ColorSwatch"
import type { DesignDNA } from "@/app/utils/quiz-types"

// Placeholder images mapped by style keywords.
const STYLE_IMAGES: Record<string, { url: string; designer: string; project: string }[]> = {
  modern: [
    { url: "https://images.unsplash.com/photo-1600210492486-724fe5c67fb0?w=600&q=80", designer: "Studio M", project: "Clementi Ave 3" },
    { url: "https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?w=600&q=80", designer: "Fuse Concept", project: "Bishan St 22" },
    { url: "https://images.unsplash.com/photo-1600585154340-be6161a56a0c?w=600&q=80", designer: "Aart Boxx", project: "Toa Payoh Lor 1" },
  ],
  scandinavian: [
    { url: "https://images.unsplash.com/photo-1616486338812-3dadae4b4ace?w=600&q=80", designer: "Nordic ID", project: "Tampines St 86" },
    { url: "https://images.unsplash.com/photo-1600566753190-17f0baa2a6c3?w=600&q=80", designer: "Hygge Design", project: "Punggol Walk" },
    { url: "https://images.unsplash.com/photo-1616594039964-ae9021a400a0?w=600&q=80", designer: "Studio Hygge", project: "Woodlands Cres" },
  ],
  japandi: [
    { url: "https://images.unsplash.com/photo-1586023492125-27b2c045efd7?w=600&q=80", designer: "Muji Living", project: "Ang Mo Kio Ave 3" },
    { url: "https://images.unsplash.com/photo-1600210491892-03d54c0aaf87?w=600&q=80", designer: "Zen Interiors", project: "Queenstown" },
    { url: "https://images.unsplash.com/photo-1615529182904-14819c35db37?w=600&q=80", designer: "Wabi Studio", project: "Sengkang East" },
  ],
  warm: [
    { url: "https://images.unsplash.com/photo-1558618666-fcd25c85f82e?w=600&q=80", designer: "Warmth Co", project: "Bedok North" },
    { url: "https://images.unsplash.com/photo-1617104678098-de229db51175?w=600&q=80", designer: "Cosy Interiors", project: "Hougang Ave 8" },
    { url: "https://images.unsplash.com/photo-1615874959474-d609969a20ed?w=600&q=80", designer: "Nest Design", project: "Jurong West" },
  ],
  industrial: [
    { url: "https://images.unsplash.com/photo-1600607687644-aac4c3eac7f4?w=600&q=80", designer: "Raw Studio", project: "Telok Blangah" },
    { url: "https://images.unsplash.com/photo-1600585152220-90363fe7e115?w=600&q=80", designer: "Loft Works", project: "Bukit Merah" },
    { url: "https://images.unsplash.com/photo-1556228453-efd6c1ff04f6?w=600&q=80", designer: "Iron & Oak", project: "Tiong Bahru" },
  ],
  default: [
    { url: "https://images.unsplash.com/photo-1600210492486-724fe5c67fb0?w=600&q=80", designer: "Studio M", project: "Clementi Ave 3" },
    { url: "https://images.unsplash.com/photo-1616486338812-3dadae4b4ace?w=600&q=80", designer: "Nordic ID", project: "Tampines St 86" },
    { url: "https://images.unsplash.com/photo-1586023492125-27b2c045efd7?w=600&q=80", designer: "Muji Living", project: "Ang Mo Kio Ave 3" },
  ],
}

function getMatchingImages(dna: DesignDNA) {
  const styleLower = dna.primaryStyle.toLowerCase()
  for (const [key, images] of Object.entries(STYLE_IMAGES)) {
    if (key !== 'default' && styleLower.includes(key)) return images
  }
  // Check traits
  for (const trait of dna.traits) {
    const t = trait.toLowerCase()
    if (STYLE_IMAGES[t]) return STYLE_IMAGES[t]
  }
  return STYLE_IMAGES.default
}

interface Props {
  dna: DesignDNA
  leadName?: string
  onRestart: () => void
}

export function StyleQuizResults({ dna, leadName, onRestart }: Props) {
  const firstName = leadName?.split(" ")[0] || "there"
  const matchingImages = getMatchingImages(dna)

  const handleDownloadGuide = () => {
    const guide = [
      `# Your Design DNA — ${dna.primaryStyle}`,
      ``,
      `Hi ${firstName}, here's your personalized interior styling profile.`,
      ``,
      `## Style Profile`,
      `- **Primary Style:** ${dna.primaryStyle}`,
      `- **Color Profile:** ${dna.colorProfile}`,
      `- **Layout Preference:** ${dna.layoutPreference}`,
      ``,
      `## Style Traits`,
      dna.traits.map(t => `- ${t}`).join('\n'),
      ``,
      `## Style Match`,
      ...Object.entries(dna.matchPercentages).map(([s, p]) => `- ${s}: ${p}%`),
      ``,
      `## Color Palette`,
      dna.paletteColors.join(', '),
      ``,
      `---`,
      `Generated by Network — Find interior designers at network.sg`,
    ].join('\n')

    const blob = new Blob([guide], { type: 'text/markdown' })
    const url = URL.createObjectURL(blob)
    const a = document.createElement('a')
    a.href = url
    a.download = 'your-design-dna.md'
    a.click()
    URL.revokeObjectURL(url)
  }

  return (
    <div className="max-w-[700px] mx-auto px-4 py-8 md:py-16">
      <motion.div
        initial={{ opacity: 0, y: 12 }}
        animate={{ opacity: 1, y: 0 }}
        transition={{ duration: 0.3 }}
        className="text-center mb-10"
      >
        <div className="inline-flex items-center gap-2 mb-4">
          <Sparkles className="w-4 h-4 text-[#9a9790]" />
          <span className="font-['DM_Sans',sans-serif] font-semibold text-[11px] text-[#9a9790] uppercase tracking-[0.12em]">
            Your results are ready
          </span>
        </div>
        <h1 className="font-['EB_Garamond',Georgia,serif] font-normal text-[32px] md:text-[44px] text-[#0f0f0d] leading-[1.15] mb-2">
          {firstName}, your Design DNA is
        </h1>
        <div className="mt-3">
          <QuizBadge variant="accent" className="text-[14px] px-5 py-2 normal-case tracking-normal font-medium">
            {dna.primaryStyle}
          </QuizBadge>
        </div>
      </motion.div>

      {/* MATCHING PROJECTS */}
      <motion.div
        initial={{ opacity: 0, y: 12 }}
        animate={{ opacity: 1, y: 0 }}
        transition={{ duration: 0.3, delay: 0.08 }}
        className="mb-4"
      >
        <div className="flex items-center justify-between mb-4">
          <h3 className="font-['EB_Garamond',Georgia,serif] font-normal text-[20px] text-[#0f0f0d]">
            Projects that match your style
          </h3>
          <span className="font-['DM_Sans',sans-serif] font-semibold text-[11px] text-[#9a9790] uppercase tracking-[0.12em]">
            {dna.primaryStyle}
          </span>
        </div>
        <div className="grid grid-cols-3 gap-[6px]">
          {matchingImages.map((img, i) => (
            <motion.div
              key={i}
              initial={{ opacity: 0, scale: 0.96 }}
              animate={{ opacity: 1, scale: 1 }}
              transition={{ duration: 0.3, delay: 0.12 + i * 0.06 }}
              className="relative rounded-[10px] overflow-hidden aspect-[4/3] group cursor-pointer"
            >
              <img
                src={img.url}
                alt={`${img.project} by ${img.designer}`}
                className="w-full h-full object-cover transition-transform duration-500 ease-out group-hover:scale-[1.06]"
              />
              <div className="absolute inset-0 bg-gradient-to-t from-black/70 via-black/20 to-transparent opacity-0 group-hover:opacity-100 transition-opacity duration-300" />
              <div className="absolute bottom-0 left-0 right-0 p-3 opacity-0 group-hover:opacity-100 transition-opacity duration-300">
                <span className="font-['DM_Sans',sans-serif] font-medium text-[11px] text-white block">
                  {img.project}
                </span>
                <span className="font-['DM_Sans',sans-serif] text-[10px] text-white/60">
                  by {img.designer}
                </span>
              </div>
            </motion.div>
          ))}
        </div>
        <p className="font-['DM_Sans',sans-serif] text-[11px] text-[#9a9790] mt-3 text-center">
          Showing placeholder projects &middot; Real designer portfolios coming soon
        </p>
      </motion.div>

      {/* Style Match Percentages */}
      <motion.div
        initial={{ opacity: 0, y: 12 }}
        animate={{ opacity: 1, y: 0 }}
        transition={{ duration: 0.3, delay: 0.15 }}
        className="bg-[#fafaf8] rounded-[12px] border border-[#d8d3c8] p-6 md:p-8 mb-4"
      >
        <h3 className="font-['EB_Garamond',Georgia,serif] font-normal text-[20px] text-[#0f0f0d] mb-5">
          Style Match
        </h3>
        <div className="space-y-4">
          {Object.entries(dna.matchPercentages).map(([style, pct], i) => (
            <div key={style}>
              <div className="flex justify-between mb-1.5">
                <span className="font-['DM_Sans',sans-serif] text-[13px] text-[#0f0f0d]">{style}</span>
                <span className="font-['DM_Sans',sans-serif] font-medium text-[13px] text-[#9a9790]">{pct}%</span>
              </div>
              <div className="w-full h-[4px] bg-[#e8e4db] rounded-full overflow-hidden">
                <motion.div
                  className="h-full bg-[#0f0f0d] rounded-full"
                  initial={{ width: 0 }}
                  animate={{ width: `${pct}%` }}
                  transition={{ duration: 0.6, delay: 0.25 + i * 0.08, ease: [0.22, 1, 0.36, 1] }}
                />
              </div>
            </div>
          ))}
        </div>
      </motion.div>

      {/* Color Profile & Layout */}
      <div className="grid grid-cols-1 md:grid-cols-2 gap-4 mb-4">
        <motion.div
          initial={{ opacity: 0, y: 12 }}
          animate={{ opacity: 1, y: 0 }}
          transition={{ duration: 0.3, delay: 0.25 }}
          className="bg-[#fafaf8] rounded-[12px] border border-[#d8d3c8] p-6"
        >
          <h3 className="font-['EB_Garamond',Georgia,serif] font-normal text-[20px] text-[#0f0f0d] mb-4">
            Color Profile
          </h3>
          <p className="font-['DM_Sans',sans-serif] text-[13px] text-[#6b6860] mb-4">{dna.colorProfile}</p>
          <div className="flex gap-2">
            {dna.paletteColors.map((color, i) => (
              <ColorSwatch key={i} color={color} size={36} showLabel />
            ))}
          </div>
        </motion.div>

        <motion.div
          initial={{ opacity: 0, y: 12 }}
          animate={{ opacity: 1, y: 0 }}
          transition={{ duration: 0.3, delay: 0.3 }}
          className="bg-[#fafaf8] rounded-[12px] border border-[#d8d3c8] p-6"
        >
          <h3 className="font-['EB_Garamond',Georgia,serif] font-normal text-[20px] text-[#0f0f0d] mb-4">
            Layout Preference
          </h3>
          <p className="font-['EB_Garamond',Georgia,serif] text-[24px] text-[#0f0f0d] mb-2">
            {dna.layoutPreference}
          </p>
          <p className="font-['DM_Sans',sans-serif] text-[12px] text-[#6b6860] leading-[1.6]">
            Your ideal space balances openness with purpose.
          </p>
        </motion.div>
      </div>

      {/* Traits */}
      <motion.div
        initial={{ opacity: 0, y: 12 }}
        animate={{ opacity: 1, y: 0 }}
        transition={{ duration: 0.3, delay: 0.35 }}
        className="bg-[#fafaf8] rounded-[12px] border border-[#d8d3c8] p-6 md:p-8 mb-6"
      >
        <h3 className="font-['EB_Garamond',Georgia,serif] font-normal text-[20px] text-[#0f0f0d] mb-4">
          Your Style Traits
        </h3>
        <div className="flex flex-wrap gap-2">
          {dna.traits.map(trait => (
            <span
              key={trait}
              className="bg-[#e8e4db] border border-[#d8d3c8] rounded-[100px] px-4 py-1.5 font-['DM_Sans',sans-serif] text-[12px] text-[#0f0f0d]"
            >
              {trait}
            </span>
          ))}
        </div>
      </motion.div>

      {/* Lead-gen CTA card */}
      <motion.div
        initial={{ opacity: 0, y: 12 }}
        animate={{ opacity: 1, y: 0 }}
        transition={{ duration: 0.3, delay: 0.4 }}
        className="bg-[#0f0f0d] rounded-[12px] p-6 md:p-8 mb-8 text-center"
      >
        <h3 className="font-['EB_Garamond',Georgia,serif] font-normal text-[22px] text-white leading-[1.3] mb-2">
          Ready to bring your style to life?
        </h3>
        <p className="font-['DM_Sans',sans-serif] text-[12px] text-white/55 leading-[1.6] mb-5 max-w-[380px] mx-auto">
          We'll match you with vetted interior designers who specialize in {dna.primaryStyle} — based on your Design DNA.
        </p>
        <div className="flex flex-col sm:flex-row items-center justify-center gap-3">
          <button className="bg-[#fafaf8] text-[#0f0f0d] rounded-[100px] px-7 py-3 font-['DM_Sans',sans-serif] font-medium text-[13px] hover:opacity-80 active:scale-[0.98] transition-all duration-150 cursor-pointer">
            Get matched with designers
          </button>
          <button
            onClick={handleDownloadGuide}
            className="flex items-center gap-2 text-white/60 font-['DM_Sans',sans-serif] text-[12px] hover:text-white/80 transition-colors duration-150 cursor-pointer"
          >
            <Download className="w-3.5 h-3.5" /> Download style guide
          </button>
        </div>
      </motion.div>

      {/* Secondary CTAs */}
      <motion.div
        initial={{ opacity: 0, y: 12 }}
        animate={{ opacity: 1, y: 0 }}
        transition={{ duration: 0.3, delay: 0.45 }}
        className="flex flex-col sm:flex-row items-center justify-center gap-4"
      >
        <Link to="/mood-board/create">
          <PillButton size="md">Create Mood Board</PillButton>
        </Link>
        <button
          onClick={onRestart}
          className="font-['DM_Sans',sans-serif] text-[13px] text-[#6b6860] hover:opacity-60 transition-opacity duration-150 cursor-pointer"
        >
          Retake Quiz
        </button>
      </motion.div>
    </div>
  )
}
